title: Robotics Simplified
description: Intuitive explanations of robotics concepts.
baseurl: "/"
url: "https://xiaoxiae.github.io"

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

search_enabled: true

# the upper right navigation
aux_links:
  "PDF Version":
    - "https://xiaoxiae.github.io/Robotics-Simplified-Website/assets/pdf/website.pdf"
  "GitHub":
    - "https://github.com/xiaoxiae/Robotics-Simplified-Website"
  "Whitepaper":
    - "https://github.com/xiaoxiae/soc-paper-2019"

color_scheme: nil

plugins:
  - jekyll-last-modified-at
