title: Robotics Simplified
description: Intuitive explanation of robotics concepts.
baseurl: "/" # site subpath
url: "http://robotics-simplified.com" # the base hostname & protocol for the site

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "PDF Version":
    - "assets/pdf/website.pdf"
  "Project GitHub":
    - "https://github.com/xiaoxiae/Robotics-Simplified-Website"

color_scheme: nil
